title: CV | Bruno Bonagura
description:  My DevOps Engineer resume
url: https://jekyll-cv.stavrospanakakis.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
